#! /usr/bin/env bash
OLA_PATH=/opt/ola
java -Djava.library.path="$OLA_PATH"/lib -Dfile.encoding=utf8 -Xmx1024m -splash:"$OLA_PATH"/webpages/Images/svenskorientering.gif -cp "$OLA_PATH"/lib/olaserver.jar;"$OLA_PATH"/lib/* soft.ola.server.Server"
